A=load("oem719-202203170900-2.bin.err");

[m,n]=size(A);
k=0;

T=A(:,2);
X =A(:,3);
Y =A(:,4);
Z =A(:,5);
B =A(:,6);
L =A(:,7);
H =A(:,8);
GPSCLK =A(:,9);
BDSCLK =A(:,10);
PDOP =A(:,11);
sigma =A(:,12);
clockVelocity =A(:,13);
VDOT =A(:,14);
SigmaDOT =A(:,15);
GPSSat =A(:,16);
BDSSat =A(:,17);
Sat =A(:,18);
VX =A(:,19);
VY =A(:,20);
VZ =A(:,21);
dX =A(:,22);
dY =A(:,23);
dZ =A(:,24);
dB =A(:,25);
dL =A(:,26);
dH =A(:,27);
E =A(:,28);
N =A(:,29);
U =A(:,30);
HDOP =A(:,31);
VDOP =A(:,32);
PS=A(:,33);
% 

figure(1);
subplot(3,1,1);
plot(T,X);
xlabel("time/s");
ylabel("X/m");
subplot(3,1,2);
plot(T,Y);
xlabel("time/s");
ylabel("Y/m");
subplot(3,1,3);
plot(T,Z);
xlabel("time/s");
ylabel("Z/m");

figure(2);
subplot(3,1,1);
plot(T,B);
xlabel("time/s");
ylabel("B/°");
subplot(3,1,2);
plot(T,L);
xlabel("time/s");
ylabel("L/°");
subplot(3,1,3);
plot(T,H);
xlabel("time/s");
ylabel("H/m");

figure(3);
subplot(2,1,1);
plot(T,GPSCLK);
xlabel("time/s");
ylabel("GPSClk/m");
subplot(2,1,2);
plot(T,BDSCLK);
xlabel("time/s");
ylabel("BDSClk/m");

figure(4);
subplot(2,1,1);
plot(T,PDOP);
xlabel("time/s");
ylabel("PDOP");
subplot(2,1,2);
plot(T,sigma);
xlabel("time/s");
ylabel("sigma/m");

figure(5);
subplot(3,1,1);
plot(T,GPSSat,"*",'MarkerFaceColor','red');
xlabel("time/s");
ylabel("GPSSatNum");
subplot(3,1,2);
plot(T,BDSSat,"*",'MarkerFaceColor','green');
xlabel("time/s");
ylabel("BDSSatNum");
subplot(3,1,3);
plot(T,Sat,"*",'MarkerFaceColor','black');
xlabel("time/s");
ylabel("SatNum");

figure(6);
subplot(3,1,1);
plot(T,VX);
xlabel("time/s");
ylabel("VX/m/s");
subplot(3,1,2);
plot(T,VY);
xlabel("time/s");
ylabel("VY/m/s");
subplot(3,1,3);
plot(T,VZ);
xlabel("time/s");
ylabel("VZ/m/s");

figure(7);
subplot(3,1,1);
plot(T,VDOT);
xlabel("time/s");
ylabel("VDOT");
subplot(3,1,2);
plot(T,SigmaDOT);
xlabel("time/s");
ylabel("YSigmaDOT/m/s");
subplot(3,1,3);
plot(T,clockVelocity);
xlabel("time/s");
ylabel("clockVelocity/m/s");

figure(8);
subplot(3,1,1);
plot(T,dX);
xlabel("time/s");
ylabel("dX/m");
subplot(3,1,2);
plot(T,dY);
xlabel("time/s");
ylabel("dY/m");
subplot(3,1,3);
plot(T,dZ);
xlabel("time/s");
ylabel("dZ/m");

figure(9);
subplot(3,1,1);
plot(T,dB);
xlabel("time/s");
ylabel("dB/°");
subplot(3,1,2);
plot(T,dL);
xlabel("time/s");
ylabel("dL/°");
subplot(3,1,3);
plot(T,dH);
xlabel("time/s");
ylabel("dH/m");

figure(10)
subplot(3,1,1);
plot(T,E);
xlabel("time/s");
ylabel("E/m");
subplot(3,1,2);
plot(T,N);
xlabel("time/s");
ylabel("N/m");
subplot(3,1,3);
plot(T,U);
xlabel("time/s");
ylabel("U/m");

figure(11);
plot(E,N);
xlabel("E/m");ylabel("N/m");
title("轨迹");

figure(12);
subplot(2,1,1);
plot(T,HDOP);
xlabel("time/s");
ylabel("HDOP");
title("平面精度衰减因子");
subplot(2,1,2);
plot(T,VDOP);
xlabel("time/s");
ylabel("VDOP");
title("高程精度衰减因子");
figure(13);
plot(T,PS);
xlabel("time/s");
ylabel("m");
title("三维点位误差");